// Types shared between main and renderer processes
// Core types are re-exported from @craft-agent/core

// Re-export core types
export type {
  Message,
  MessageRole,
  TypedError,
  TokenUsage,
  Workspace,
  SessionMetadata,
  SubAgentMetadata,
  StoredAttachment,
} from '../../../../packages/core/src/types/index.ts';

// Re-export agent types for Info dialog
export type {
  SubAgentDefinition,
  McpServerConfig,
  ApiConfig,
} from '../../../../src/agents/types.ts';
export { generateMessageId } from '../../../../packages/core/src/types/index.ts';

/**
 * Auth requirements for an agent - lists MCP servers and APIs needing credentials
 */
export interface AgentAuthRequirements {
  mcpServers: Array<{ name: string; url: string; requiresAuth?: boolean }>
  apis: Array<{ name: string; auth?: { type: string; credentialLabel?: string; secretLabel?: string } }>
}

/**
 * OAuth result from main process
 */
export interface OAuthResult {
  success: boolean
  error?: string
}

/**
 * MCP connection validation result
 */
export interface McpValidationResult {
  success: boolean
  error?: string
  tools?: string[]
}

/**
 * Agent setup status - indicates if agent needs setup or auth
 */
export interface AgentSetupStatus {
  needsSetup: boolean  // Agent definition has never been extracted
  needsAuth: boolean   // Definition exists but credentials are missing
  reason?: string
}

/**
 * MCP server with auth status for Info dialog
 */
export interface McpServerWithAuthStatus {
  name: string
  url: string
  requiresAuth?: boolean
  hasAuth: boolean  // Whether credentials have been provided
  tools?: string[]
}

/**
 * API with auth status for Info dialog
 */
export interface ApiWithAuthStatus {
  name: string
  baseUrl: string
  auth?: { type: string; credentialLabel?: string; secretLabel?: string }
  hasAuth: boolean  // Whether credentials have been provided
}

/**
 * Auth status for an agent's MCP servers and APIs
 */
export interface AgentAuthStatus {
  mcpServers: McpServerWithAuthStatus[]
  apis: ApiWithAuthStatus[]
}

/**
 * File attachment for sending with messages
 * Matches the FileAttachment interface from src/utils/files.ts
 */
export interface FileAttachment {
  type: 'image' | 'text' | 'pdf' | 'office' | 'unknown'
  path: string
  name: string
  mimeType: string
  base64?: string  // For images, PDFs, and Office files
  text?: string    // For text files
  size: number
  thumbnailBase64?: string  // Quick Look thumbnail (generated by Electron main process)
}

// Import types needed for Session interface
import type { Message } from '../../../../packages/core/src/types/index.ts';

/**
 * Electron-specific Session type (includes runtime state)
 * Extends core Session with messages array and processing state
 */
export interface Session {
  id: string
  workspaceId: string
  workspaceName: string
  name?: string  // User-defined or AI-generated session name
  lastMessageAt: number
  messages: Message[]
  isProcessing: boolean
  // Inbox/Archive features (from core SessionMetadata)
  agentId?: string
  agentName?: string
  isArchived?: boolean
}

// Events sent from main to renderer
export type SessionEvent =
  | { type: 'text_delta'; sessionId: string; delta: string }
  | { type: 'text_complete'; sessionId: string; text: string }
  | { type: 'tool_start'; sessionId: string; toolName: string; toolUseId: string; toolInput: Record<string, unknown> }
  | { type: 'tool_result'; sessionId: string; toolUseId: string; toolName: string; result: string }
  | { type: 'error'; sessionId: string; error: string }
  | { type: 'typed_error'; sessionId: string; error: import('../../../../packages/core/src/types/index.ts').TypedError }
  | { type: 'complete'; sessionId: string }
  | { type: 'status'; sessionId: string; message: string }
  | { type: 'title_generated'; sessionId: string; title: string }

// IPC channel names
export const IPC_CHANNELS = {
  // Session management
  GET_SESSIONS: 'sessions:get',
  CREATE_SESSION: 'sessions:create',
  DELETE_SESSION: 'sessions:delete',
  RENAME_SESSION: 'sessions:rename',
  SEND_MESSAGE: 'sessions:sendMessage',
  CANCEL_PROCESSING: 'sessions:cancel',
  ARCHIVE_SESSION: 'sessions:archive',
  UNARCHIVE_SESSION: 'sessions:unarchive',

  // Workspace management
  GET_WORKSPACES: 'workspaces:get',

  // Agent management
  GET_AGENTS: 'agents:get',
  REFRESH_AGENTS: 'agents:refresh',
  CHECK_AGENT_AUTH: 'agents:checkAuth',
  GET_AGENT_SETUP_STATUS: 'agents:getSetupStatus',
  GET_AGENT_AUTH_STATUS: 'agents:getAuthStatus',
  GET_AGENT_DEFINITION: 'agents:getDefinition',
  RELOAD_AGENT: 'agents:reloadAgent',
  RESET_AGENT: 'agents:resetAgent',

  // Agent authentication
  GET_AGENT_AUTH_REQUIREMENTS: 'agents:getAuthRequirements',
  START_MCP_OAUTH: 'agents:startMcpOAuth',
  SAVE_MCP_BEARER: 'agents:saveMcpBearer',
  SAVE_API_CREDENTIALS: 'agents:saveApiCredentials',
  VALIDATE_MCP_CONNECTION: 'agents:validateMcpConnection',

  // Events from main to renderer
  SESSION_EVENT: 'session:event',

  // File operations
  READ_FILE: 'file:read',
  OPEN_FILE_DIALOG: 'file:openDialog',
  READ_FILE_ATTACHMENT: 'file:readAttachment',
  STORE_ATTACHMENT: 'file:storeAttachment',
  GENERATE_THUMBNAIL: 'file:generateThumbnail',

  // Theme
  GET_SYSTEM_THEME: 'theme:getSystemPreference',
  SYSTEM_THEME_CHANGED: 'theme:systemChanged',

  // System
  GET_VERSIONS: 'system:versions',

  // Shell operations (open external URLs/files)
  OPEN_URL: 'shell:openUrl',
  OPEN_FILE: 'shell:openFile',
} as const

// Re-import types for ElectronAPI
import type { Workspace, SessionMetadata, StoredAttachment as StoredAttachmentType } from '../../../../packages/core/src/types/index.ts';
import type { SubAgentMetadata } from '../../../../packages/core/src/types/index.ts';

// Type-safe IPC API exposed to renderer
export interface ElectronAPI {
  // Session management
  getSessions(): Promise<Session[]>
  createSession(workspaceId: string, agentId?: string, agentName?: string): Promise<Session>
  deleteSession(sessionId: string): Promise<void>
  renameSession(sessionId: string, name: string): Promise<void>
  sendMessage(sessionId: string, message: string, attachments?: FileAttachment[], storedAttachments?: StoredAttachmentType[]): Promise<void>
  cancelProcessing(sessionId: string): Promise<void>
  archiveSession(sessionId: string): Promise<void>
  unarchiveSession(sessionId: string): Promise<void>

  // Workspace management
  getWorkspaces(): Promise<Workspace[]>

  // Agent management
  getAgents(workspaceId: string): Promise<SubAgentMetadata[]>
  refreshAgents(workspaceId: string): Promise<SubAgentMetadata[]>
  checkAgentAuth(workspaceId: string, agentId: string): Promise<{ needsAuth: boolean; reason?: string }>
  getAgentSetupStatus(workspaceId: string, agentId: string): Promise<AgentSetupStatus>
  getAgentAuthStatus(workspaceId: string, agentId: string): Promise<AgentAuthStatus>
  getAgentDefinition(workspaceId: string, agentId: string): Promise<import('../../../../src/agents/types.ts').SubAgentDefinition | null>
  reloadAgent(workspaceId: string, agentId: string): Promise<boolean>
  resetAgent(workspaceId: string, agentId: string): Promise<boolean>

  // Agent authentication
  getAgentAuthRequirements(workspaceId: string, agentId: string): Promise<AgentAuthRequirements>
  startMcpOAuth(workspaceId: string, agentId: string, serverUrl: string, serverName: string): Promise<OAuthResult>
  saveMcpBearer(workspaceId: string, agentId: string, serverName: string, token: string): Promise<void>
  saveApiCredentials(workspaceId: string, agentId: string, apiName: string, credential: string): Promise<void>
  validateMcpConnection(serverUrl: string, accessToken?: string): Promise<McpValidationResult>

  // Event listener
  onSessionEvent(callback: (event: SessionEvent) => void): () => void

  // File operations
  readFile(path: string): Promise<string>
  openFileDialog(): Promise<string[]>
  readFileAttachment(path: string): Promise<FileAttachment | null>
  storeAttachment(sessionId: string, attachment: FileAttachment): Promise<import('../../../../packages/core/src/types/index.ts').StoredAttachment>
  generateThumbnail(base64: string, mimeType: string): Promise<string | null>

  // Theme
  getSystemTheme(): Promise<boolean>
  onSystemThemeChange(callback: (isDark: boolean) => void): () => void

  // System
  getVersions(): { node: string; chrome: string; electron: string }

  // Shell operations
  openUrl(url: string): Promise<void>
  openFile(path: string): Promise<void>
}

declare global {
  interface Window {
    electronAPI: ElectronAPI
  }
}
